### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by macor161**
I fixed the app roles and added a dummy frontend so the app could compile.

### CODE REVIEW

**Comment by vporton** [comment]
After merging @macor161 PR it starts without an error when trying `npm run start:template`:

It is quite weird. **Why** have your changes fixed the error?!

I also needed `npm i react`, `npm i @aragon/api-react`, `npm i react-dom`, `npm i @aragon/ui`, `npm i styled-components`, `npm i @aragon/api`.

**Comment by vporton** [comment]
@macor161 But [my real software](https://github.com/vporton/courts/commit/38c1afca095812668d7e2aec209d3dc401f341ca) does not start successfully anyway, even if I apply proposed in the discussion fixes.

By the way for the "real software", the error is: `Invalid number of parameters for "undefined". Got 0 expected 1!`

Why `undefined`?

Help me to find bug(s) (either in Aragon or my software) that prevent my real software to start.

**Comment by macor161** [comment]
@vporton Sure I can help you out in the chat tomorrow. Let me know if you were able to solve your problem on the other branch.

**Comment by vporton** [comment]
@macor161 I don't understand which "other branch" you refer to. First, is it a branch of `aragon-template-args-bug` or of `courts` repo? Which branch? which problem exactly?

Also, if you ask if I made `aragon-template-args-bug` to work, then te answer is yes. But my real software `courts` does not work.

**Comment by macor161** [comment]
@vporton Ah I thought you were talking about the other branch on this repo. No problem, I will be in the chat tomorrow at around 8am EST if you need help 🙂

**Pull request merged**
